[env]
AWS_CLI_AUTO_PROMPT = "on-partial"
AWS_DEFAULT_REGION = "eu-central-1"

[tools]
awscli = "latest"

[tasks.setup-check]
description = "first"
run = "aws sts get-caller-identity"
alias = "check"

[tasks.autocompletion]
description = "enable autocompletion for AWS CLI"
run = "complete -C $(which aws_completer) aws"
